---
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "letsrockthefuture/dependabot-reviewers"

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "letsrockthefuture/dependabot-reviewers"
