---
name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: '$RESOLVED_VERSION'

categories:
- title: '🚀 Features'
  labels:
  - 'feature'
  - 'enhancement'
- title: '🐛 Bug fixes'
  labels:
  - 'fix'
  - 'bugfix'
  - 'bug'
  - 'hotfix'
- title: '🧰 Maintenance'
  labels:
  - 'chore'


version-resolver:
  major:
    labels:
    - 'major'
  minor:
    labels:
    - 'minor'
    - 'enhancement'
  patch:
    labels:
    - 'patch'
    - 'fix'
    - 'hotfix'
    - 'bug'
    - 'bugfix'
  default: 'patch'

change-template: |
  <details>
    <summary>$TITLE @$AUTHOR (#$NUMBER)</summary>

    $BODY
  </details>

template: |
  $CHANGES